### ISSUE TITLE
Question - How to feed it?

### ISSUE THREAD

**Issue by nik-k** [RomanSixty/newfilmdb#1]
Hi Roman,

how do i feed the database or does it read the filetree?

Thanks in advance

**Comment by RomanSixty** [comment]
You initialize the SQLite database by uncommenting [line 14 in lib_sqlitedb.php](https://github.com/RomanSixty/newfilmdb/blob/master/lib_sqlitedb.php#L14). Afterwards you can open the tool in your browser and start adding movies by clicking on the plus icon in the lower right side of the screen.
